# Simple linear regression

## Import the relevant libraries

In [35]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

from sklearn.linear_model import LinearRegression

## Load the data

In [36]:
df = pd.read_csv('1.01.+Simple+linear+regression.csv', sep = ',')
df.head()

SAT   GPA
0  1714  2.40
1  1664  2.52
2  1760  2.54
3  1685  2.74
4  1693  2.83

In [37]:
df.describe()

SAT        GPA
count    84.000000  84.000000
mean   1845.273810   3.330238
std     104.530661   0.271617
min    1634.000000   2.400000
25%    1772.000000   3.190000
50%    1846.000000   3.380000
75%    1934.000000   3.502500
max    2050.000000   3.810000

## Create the regression

### Declare the dependent and independent variables

In [38]:
x = df['SAT']
x.shape

(84,)

In [39]:
x_matrix = x.values.reshape(-1,1)
x_matrix.shape

(84, 1)

In [40]:
y = df['GPA']
y.shape

(84,)

### Regression itself

In [41]:
reg = LinearRegression()

In [42]:
reg.fit(x_matrix,y)

LinearRegression()

###  R-squared

In [49]:
reg.score(x_matrix,y)

0.40600391479679765

### Coefficients

In [52]:
reg.coef_

array([0.00165569])

### Intercept  = statsmodels.api regression.summary const

In [59]:
reg.intercept_

0.2750402996602803

### Making Predictions

In [65]:
reg.predict(np.array([1740]).reshape(-1,1))

array([3.15593751])

reg.predict only take array type as input

In [68]:
new_data = pd.DataFrame(data = [1740,1760], columns = ['SAT'])
new_data

SAT
0  1740
1  1760

In [70]:
reg.predict(new_data.values)

array([3.15593751, 3.18905127])

In [71]:
new_data['predicted_GPA'] = reg.predict(new_data.values)

In [72]:
new_data

SAT  predicted_GPA
0  1740       3.155938
1  1760       3.189051